version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_delivery
    ports:
      - '3001:3000' # Host port 3001 maps to container port 3000
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app # Optional for dev
    command: ['npm', 'run', 'start'] # Matches package.json
